/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }


    @Test
    public void TestBuyuktur(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1,2,3,4,5,6));
        assertTrue(App.eleman_karsilastir(array, 3, 2, ">"));
    }

    @Test
    public void TestKucukDegildir(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(2,4,1,4,5,6,7));
        assertFalse(App.eleman_karsilastir(array, 4, 1, "<"));
    }

    @Test
    public void TestYanlisSembol(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(5,4,2,4,1,3));
        assertFalse(App.eleman_karsilastir(array, 5, 2, "-"));
    }

    @Test
    public void TestBosListe(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList());
        assertFalse(App.eleman_karsilastir(array, 3, 6, "<"));
    }

    @Test
    public void TestBulunmayanIndex(){
        ArrayList<Integer> array = new ArrayList<>(Arrays.asList(0,1,2));
        assertFalse(App.eleman_karsilastir(array, 4, 8, ">"));
    }
}
