/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev3;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean eleman_karsilastir(ArrayList<Integer> array, int index, int index2, String sembol){
        boolean cikti=false;
        if((array.size()<=index) || (array.size()<=index2)){

        }
        else{
            if(sembol.equals(">")){
                if(array.get(index)>=array.get(index2)){
                    cikti=true;
                }
                else{
                    cikti=false;
                }
                
            }
            else if(sembol.equals("<")){
                if(array.get(index)<array.get(index2)){
                    cikti=true;
                }
                else{
                    cikti=false;
                }
            }
            

        }

        return cikti;
    }
}
